name: Test Scripts on RPi Simulator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            bash StableInstall_RPiShinyServer.sh
            bash Uninstall_RPiShinyServer.sh